gama/urls.py
from django.urls import path

from . import views

app_name = "gama"
urlpatterns = [
    path("", views.index, name="index"),
    path("analysis", views.analysis, name="analysis"),
    path("error/<str:errtype>/", views.error, name="error"),
    path("export_results/", views.export_results, name="export_results"),
    path("about/", views.about, name="about"),
    path("results/", views.analysis_results, name="analysis_result"),
    path('clear-session/', views.clear_session, name='clear_session'),
    path('bulk_analysis/', views.bulk_analysis, name='bulk_analysis'),
]

gamaweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # Nécessaire pour set_language
]

urlpatterns += i18n_patterns(
    path('gama/', include('gama.urls')),
    path('admin/', admin.site.urls),
)

gama/models.py
from django.db import models

# Create your models here.

gama/views.py
from django.shortcuts import render

# Create your views here.

from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.utils import translation

from pathlib import Path
import subprocess
import zipfile
import time
import uuid
import re
import csv
import tempfile
import json
import os
import base64

from gumper import config as gcf
from gumper.gumper_client_web import main as gumper_main


DBG = False
DEFAULTS_TO_TRANSLATE = {
    "corpus_name": ["Unnamed corpus"],
    "doc_name": ["Untitled"],
    "doc_subtitle": ["—"],
    "author": ["Unknown"],
    "date": ["—"],
}

def clear_session(request):
    """
    Supprime les données d'analyse stockées en session et redirige vers la page index
    """
    try:
        del request.session['analysis_data']
    except KeyError:
        pass
    return redirect('gama:index')

def handle_language(request):
    """
    Gestion des langues
    """

    # Initialise lang à None
    lang = None

    # Récupère les langues envoyées en POST (menu de langues)
    if request.method == "POST":
        lang = request.POST.get("language")

    # Si une langue est récupérée (=/ None) on active cette langue
    # (--> changement de langue d'une page via le menu de langues)
    if lang:
        translation.activate(lang)
        request.LANGUAGE_CODE = lang

    # Sinon (aucune langue passée en POST) on récupère la langue enregistrée par Django
    # (--> simple navigation ou rechargement d'une page)
    else:
        lang = translation.get_language()
        translation.activate(lang)

    # Renvoi la langue utilisée
    return lang


def load_example_poems():
    """
    Charge le fichier JSON contenant des exemples de poèmes.
    """
    example_path = os.path.join(settings.BASE_DIR, "gama", "ext_data", "ex_poem.json")
    try:
        with open(example_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}

def index(request):
    """
    Page d'accueil de l'application.

    Étapes :
    1. Gére la langue via handle_language.
    2. Charge les poèmes d'exemple pour l'affichage.
    3. Récupère les données précédemment saisies en session
       (si l'utilisateur revient sur la page les champs restent pré-remplis).
    4. Passe les données au template index.html pour affichage.
    """
    #return HttpResponse("Hello, world. You're at the gama index.")

    # Gestion de la langue
    handle_language(request)

    # Chargement des poèmes exemples
    example_poems = load_example_poems()

    # Récupération des metadata depuis la session
    initial_data = request.session.get('analysis_data', {})

    # Rendu template html avec le context
    return render(request, "gama/index.html", {
            "example_poems": example_poems,
            "initial_data": initial_data,
    })

def translate_if_default(value, key):
    """
    Traduit une valeur uniquement si elle correspond à une valeur par défaut
    définie dans DEFAULTS_TO_TRANSLATE.
    """
    if value in DEFAULTS_TO_TRANSLATE.get(key, []):
        return _(value)
    return value

def analysis(request):
    """
    Traite le POST d'une analyse de texte.

    Rôle :
    1. Vérifie et valide le texte soumis (taille, format des vers, etc.).
    2. Récupère et stocke les metadata dans la session.
       (utile pour conserver les valeurs si l'utilisateur change de langue)
    3. Crée un dossier unique pour l'analyse et écrit le texte en fichier.
    4. Lance le prétraitement via un script externe.
    5. Effectue l'analyse métrique via gumper_main et stocke :
       - scansion (pour affichage)
       - results_data (pour export)
    6. Redirige vers analysis_results pour afficher le résultat (PRG).

    Remarques :
    - Ne gère que le POST.
    - Les résultats sont conservés en session pour permettre changement de langue
      sans relancer l'analyse.
    """
    # Gestion de la langue via handle_language
    handle_language(request)

    # Récupère et vérifie que le texte n'est pas vide, trop long, ou contient des vers trop longs
    if request.method == "POST":
        text = request.POST.get("text", "")
        if not text:
            return redirect("gama:error", errtype="empty")
        if len(text) > 4500:
            return redirect("gama:error", errtype="too_long")
        if any(len(line.strip()) > 200 for line in text.splitlines() if line.strip()):
            return redirect("gama:error", errtype="not_verse")

        # Récupération des métadonnées (or "valeur par défaut" si champ vide)
        corpus_name_key = request.POST.get("corpus_name") or "—"
        doc_name_key = request.POST.get("doc_name") or "—"
        doc_subtitle_key = request.POST.get("doc_subtitle") or "—"
        author_key = request.POST.get("author") or "Unknown"
        date_key = request.POST.get("date") or "—"

        # Stockage en session des metadata pour pouvoir changer la langue sur la page
        # (et éviter l'erreur et redirection 'empty' lors du changement)
        request.session['analysis_data'] = {
            "text": text,
            "corpus_name": corpus_name_key,
            "doc_name": doc_name_key,
            "doc_subtitle": doc_subtitle_key,
            "author": author_key,
            "date": date_key,
        }

        # ID unique et dossier de sortie
        request.session["curid"] = str(uuid.uuid4())[0:6]
        curid = request.session["curid"]
        out_dir = settings.IO_DIR / curid
        Path(out_dir).mkdir(parents=True, exist_ok=True)
        with open(out_dir / "input.txt", encoding="utf8", mode="w") as f:
            f.write(text)

        try:
            subprocess.run(
                ["python", "../preprocessing/g2s_client_running_text.py",
                 str(out_dir / "input.txt"), "-p", "-d", "-n", "-s", "-b", "001"],
                check=True,
                cwd=settings.PREPRO_DIR,
            )

            # Analyse métrique
            orig_poem_path = out_dir / "input.txt"
            prepro_poem_path = out_dir / "out_001" / "input_pp_out_norm_spa_001.txt"
            # scansion : texte formaté pour l'affichage
            # results_data : dictionnaire pour export tsv
            scansion, results_data = gumper_main(gcf, orig_poem_path, prepro_poem_path)

            # Stockage résultats de l'analyse en session
            # Pour pouvoir changer lg depuis la page de résultats (sans relancer l'analyse)
            request.session['analysis_result'] = "".join(scansion)

            # Stockage des résultats pour l'export au format tsv
            request.session['results_data'] = results_data

            # Redirection vers analysis_results selon principe PRG
            return redirect("gama:analysis_result")

        # Si erreur lors de l'analyse
        except Exception as e:
            print(f"Unexpected error during analysis: {e}")
            # Redirection vers page error.html
            return redirect("gama:error", errtype="unexpected")

    return redirect("gama:index")

def analysis_results(request):
    """
    Affiche les résultats d'une analyse de texte.

    Rôle :
    1. Récupère depuis la session :
       - `analysis_data` (texte + métadonnées)
       - `analysis_result` (scansion du texte)
    2. Si les données sont absentes, redirige vers une page d'erreur.
    3. Traduit les métadonnées par défaut si besoin,
       sans toucher aux valeurs saisies par l'utilisateur.
    4. Passe les données au template analysis.html pour affichage.

    Remarques :
    - Gère uniquement le GET.
    - Permet de changer la langue sur la page résultats sans perdre le texte ou
      les métadonnées.
    - Compatible avec le principe PRG : l'analyse est séparée de l'affichage.
    """

    # Gestion de la langue
    handle_language(request)

    # Récupération des données stockées en session
    # Permet d'afficher sans relancer l'analyse
    analysis_data = request.session.get("analysis_data")
    analysis_result = request.session.get("analysis_result")

    # Si vide et qu'on ne peut rien afficher, redirection vers page erreur 'empty'
    if not analysis_data or not analysis_result:
        return redirect("gama:error", errtype="empty")

    # Traduction des métadonnées uniquement si valeurs par défaut
    # (ne traduit pas des valeurs saisies par l'utilisateur)
    corpus_name = translate_if_default(analysis_data.get("corpus_name", "Unnamed corpus"), "corpus_name")
    doc_name = translate_if_default(analysis_data.get("doc_name", "Untitled"), "doc_name")
    doc_subtitle = translate_if_default(analysis_data.get("doc_subtitle", "—"), "doc_subtitle")
    author = translate_if_default(analysis_data.get("author", "Unknown"), "author")
    date = translate_if_default(analysis_data.get("date", "—"), "date")

    # Context pour le rendu du template analysis.html
    context = {
        "text": analysis_data.get("text", ""),
        "corpus_name": corpus_name,
        "doc_name": doc_name,
        "doc_subtitle": doc_subtitle,
        "author": author,
        "date": date,
        "result": analysis_result,
    }

    return render(request, "gama/analysis.html", context)

def error(request, errtype):
    """
    Gère l'affichage des erreurs côté utilisateur.

    Étapes :
    1. Active la langue de l'utilisateur via handle_language.
    2. Détermine le message d'erreur en fonction de `errtype` :
       - 'empty' : texte vide
       - 'too_long' : texte trop long
       - 'not_verse' : ligne trop longue / non conforme au format vers
       - autre : erreur inattendue
    3. Prépare le contexte pour le template de la page d'accueil,
       incluant des poèmes exemples pour que le sélecteur ne soit pas vide.
    4. Rendu du template approprié.
    """

    # Gestion de la langue
    handle_language(request)

    # Gestion du message selon le type d'erreur
    if errtype == "empty":

gama/templates/gama/analysis.html
{% extends "gama/base.html" %}
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<div class="row justify-content-center mb-4">
    <div class="col-12 col-md-10 col-lg-8">
        <h2 class="mb-3 mt-3">{% trans "Results" %}</h2>
<!-- Bloc métadonnées -->

        <section class="text-info-block mt-3">
            <div class="inner-content">
                <h3 class="mb-1">{%trans "Metadata" %}</h3>
                    <div class="container-fluid my-0">
                        <div class="row mb-0 metad">
                            <div class="col-md-4">
                                <strong class="me-2">{% trans "Corpus name:" %}</strong>
                                <span>{{ corpus_name }}</span>
                            </div>
                            <div class="col-md-4">
                                <strong class="me-2">{% trans "Author:" %}</strong>
                                <span>{{ author }}</span>
                            </div>
                            <div class="col-md-4">
                                <strong class="me-2">{% trans "Date:" %}</strong>
                                <span>{{ date }}</span>
                            </div>
                        </div>
                        <div class="row mb-0 metad">
                            <div class="col-md-4">
                                <strong class="me-2">{% trans "Title:" %}</strong>
                                <span>{{ doc_name }}</span>
                            </div>
                            <div class="col-md-4">
                                <strong class="me-2">{% trans "Subtitle:" %}</strong>
                                <span>{{ doc_subtitle }}</span>
                            </div>
                        </div>
                    </div>
            </div>
        </section>

<!-- Bloc tableau résultats -->

        <div class="inner-content">
            <h3 class="mb-3 mt-4">{%trans "Scansion" %}</h3>
        </div>
        <!-- Bouton Afficher/Cacher Preprocessing -->
        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="togglePreprocessing" checked>
            <label class="form-check-label" for="togglePreprocessing">
                {%trans "Show Preprocessing" %}
            </label>
        </div>
        <div class="table-responsive">
            <table id="myTable" class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="text-end">
                            #
                        </th>
                        <th scope="col" class="text-start">
                            {%trans "Original text" %}
                        </th>
                        <th scope="col" class="text-start col-preprocessing">
                            {%trans "Preprocessing" %}
                        </th>
                        <th scope="col" class="text-end">
                            {%trans "Metrical syllables" %}
                        </th>
                        <th scope="col" class="text-end" data-bs-toggle="tooltip" data-bs-placement="top"
                            title="">
                            {%trans "Stressed syllables" %}
                        </th>
                        <th scope="col" class="text-end" data-bs-toggle="tooltip" data-bs-placement="top"
                            title="{%trans 'Extra rhythmic stresses removed' %}">
                            {%trans "No extra-rhythmic" %}
                        </th>
                    </tr>
                </thead>
                <tbody>
                        {{ result|safe }}
                    </tbody>
            </table>
        </div>
        <!-- boutons retour/téléchargement !-->
        <section class="d-flex justify-content-between my-3 mt-5">
            <a href="{% url 'gama:index' %}" class="btn btn-beige me-3">{% trans "New analysis" %}</a>
            <a href="{% url 'gama:export_results' %}" class="btn btn-beige">
                {% trans "Download results (ZIP)" %}
            </a>
        </section>
    </div>
</div>


<script>
$(document).ready(function () {

    // ---------------------------
    // Récupération de la langue active Django
    // ---------------------------
    // Permet de savoir dans quelle langue afficher la table (fr, en, gl)
    window.lang = "{{ LANGUAGE_CODE }}";

    // ---------------------------
    // Chargement du fichier de traduction correspondant pour affichage du DataTable
    // ---------------------------
    const langUrls = {
        'fr': '{% static "js/i18n/datatables/fr-FR.json" %}',
        'en': '{% static "js/i18n/datatables/en-GB.json" %}',
        'gl': '{% static "js/i18n/datatables/gl-ES.json" %}',
    };

    // ---------------------------
    // Paramètres du DataTable
    // ---------------------------
    // - responsive: adapte la table aux écrans petits
    // - paging: active la pagination
    // - pageLength: nombre de lignes par page (ici 100)
    // - searching: barre de recherche
    // - ordering: tri des colonnes activé
    // - language.url: charge le JSON correspondant à la langue pour la traduction
    const table = $('#myTable').DataTable({
        responsive: true,
        paging: true,
        pageLength: 100,
        searching: true,
        ordering: true,
        language: {
            url: langUrls[window.lang] || langUrls['en'] // fallback en en si langue non trouvée
        }
    });

    // ---------------------------
    // Gestion du bouton Afficher/Cacher colonne Preprocessing
    // ---------------------------
    // Le checkbox #togglePreprocessing permet de masquer/afficher la colonne
    document.getElementById("togglePreprocessing").addEventListener("change", function () {
        const show = this.checked;  // true si coché, false sinon
        const column = table.column('.col-preprocessing'); // sélectionne la colonne via sa classe
        column.visible(show);  // montre ou cache la colonne via DataTables
        table.columns.adjust().draw();  // ajuste la largeur et redessine le tableau
    });
});

</script>


{% endblock %}

gama/templates/gama/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Galician Metrical Analyzer · GAMA{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon2.ico' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}"/>
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    <!-- <script src="{% static 'js/tablesort.js' %}"></script> !-->
</head>
<body>
    <!-- HEADER -->
    <header class="navbar-custom position-relative mb-0">
        <div class="container navbar-border d-flex justify-content-between align-items-center px-2 py-0 my-0 mb-0">
            <!-- Titre -->
            <h1 class="mb-3 site-title"><a class="site-title" href="{% url 'gama:clear_session' %}">{% trans "GAMA: Galician Metrical Analyzer" %}</a></h1>
            <!-- Container droite -->
            <div class="d-flex align-items-center gap-4">
                <!-- Liens dans navbar avant menu langues (hidden on small screens cos gonna go on sidebar) -->
                <a href="{% url 'gama:about' %}" class="navig-link d-none d-sm-inline">{% trans "About" %}</a>
                <a href="https://github.com/compellit/gamaweb" target="_blank" class="navig-link d-none d-sm-inline"><i class="bi bi-github fs-5"></i></a>
                <!-- Séparateur -->
                <span class="vertical-separator d-none d-sm-inline"></span>
                <!-- Menu langues -->
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle d-flex align-items-center" type="button" id="langDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-globe fs-5 me-1 lang-icon"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-start dropdown-lang" aria-labelledby="langDropdown">
                                <a href="#" class="dropdown-item lang-link {% if LANGUAGE_CODE == 'en' %}fw-bold{% endif %}" data-lang="en">en</a>
                                <a href="#" class="dropdown-item lang-link {% if LANGUAGE_CODE == 'fr' %}fw-bold{% endif %}" data-lang="fr">fr</a>
                                <a href="#" class="dropdown-item lang-link {% if LANGUAGE_CODE == 'gl' %}fw-bold{% endif %}" data-lang="gl">gl</a>
                        </div>
                    <!-- Formulaire pour soumettre langue via JS -->
                    <form id="lang-form" action="{% url 'set_language' %}" method="post" style="display: none;">
                        {% csrf_token %}
                        <input type="hidden" name="language" id="lang-input">
                        <input type="hidden" name="next" id="lang-next" value="{{ request.path }}">
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- <nav class="navigation-bar px-2">
        <div class="container-fluid d-flex justify-content-end gap-3">
            <a href="{% url 'gama:index' %}" class="lang-link">{% trans "Home" %}</a>
            <span class="nav-sep">•</span>
            <a href="#" class="lang-link">{% trans "About" %}</a>
        </div>
    </nav>-->

        <!-- TOGGLER pour sidebar (visible seulement en petit écran) -->
    <button id="sidebarToggle"
            class="sidebar-toggle custom-tog position-fixed top-50 start-0 translate-middle-y border-0 px-1 py-2 rounded-end shadow-sm d-md-none"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#sidebarMenu"
            aria-controls="sidebarMenu">
        <i class="bi bi-chevron-right fs-4"></i>
    </button>

    <!-- SIDEBAR (offcanvas) -->
    <div class="offcanvas offcanvas-start custom-offcanvas" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="sidebarMenuLabel">GAMA</h5>
            <button type="button" class="btn-close btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{% url 'gama:clear_session' %}" class="nav-link">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'gama:about' %}" class="nav-link">{% trans "About" %}</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'gama:about' %}" class="nav-link">GitHub</a>
                </li>
            </ul>
        </div>
    </div>

<!-- body !-->
<main class="container my-0" style="padding-bottom: 70px;">
    {% block content %}{% endblock %}
</main>

<!-- FOOTER !-->
<footer class="footer fixed-bottom py-2 bg-dark border-top w-100">
    <div class="container-fluid d-flex justify-content-evenly align-items-center flex-wrap px-0 py-0 my-0 gap-3 small-text-mobile">
        <div class="footer-left text-white d-flex align-items-center flex-shrink-1">
            <span>© 2025 COMPEL</span>
        </div>
        <div class="d-flex align-items-center">
            <span class="text-white me-2"><a href="https://cordis.europa.eu/project/id/101149659" target="_blank" rel="noopener">Grant ID: 101149659 MSCA-PF</a></span>
                <a href="https://cordis.europa.eu/project/id/101149659" target="_blank" rel="noopener">
                <img id="funded-eu" src="{% static 'img/eu-white-text.png' %}" alt="EU Funded" style="height: 50px;"/>
                </a>
        </div>
    </div>
</footer>

<!-- JAVASCRIPT -->
<script>
    // ---------------------------
    // Changement de langue via le menu de langue
    // ---------------------------
    document.querySelectorAll('.lang-link').forEach(link => {
        link.addEventListener('click', function (e) {
            e.preventDefault();
            const lang = this.dataset.lang; // Récupère la langue
            const form = document.getElementById('lang-form');
            document.getElementById('lang-input').value = lang;
            document.getElementById('lang-next').value = window.location.pathname;

            // Soumission du formulaire pour changer la langue
            fetch(form.action, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': form.querySelector('[name=csrfmiddlewaretoken]').value,
                },
                body: `language=${lang}&next=${encodeURIComponent(window.location.pathname)}`
            }).then(() => {
                // Redirection vers même page avec le nouveau préfixe de langue dans url
                // + Remplace la page courante dans l'historique au lieu d'en créer une nouvelle)
                    // (si l'utilisateur a changé plusierus fois de langue sur une page --> pas conservées dans historique
                    // empêche les retours vers une même page dans différentes langues)
                window.location.replace(`/${lang}${window.location.pathname.slice(3)}`);
            });
        });
    });

    // ---------------------------
    // Fonction permettant de récupérer un cookie
    // ---------------------------
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }

    // ---------------------------
    // Gestion du retour arrière (back button)
    // ---------------------------
    // Si la langue du cookie est différente de l'URL --> redirige dans la bonne langue
        // (ex : si l'utilisateur change de langue depuis une page et fait un back sur la page précédente,
        // celle-ci s'affiche dans la nouvelle langue)
    window.addEventListener("pageshow", function (event) {
        if (event.persisted || performance.getEntriesByType("navigation")[0].type === "back_forward") {
            const urlLang = window.location.pathname.split("/")[1]; // 'fr', 'en', 'gl'
            const cookieLang = getCookie("django_language");

            if (cookieLang && urlLang !== cookieLang) {
                const newUrl = `/${cookieLang}${window.location.pathname.slice(3)}`;
                window.location.replace(newUrl);
            }
        }
    });
    // ---------------------------
    // Menu déroulant langues
    // ---------------------------
    // Sélectionne l'élément du menu déroulant
    const dropdown = document.querySelector('.dropdown');
    // Affiche le menu Bootstrap au hover
    dropdown.addEventListener('mouseenter', () => {
        // Récupère ou crée l'instance Bootstrap Dropdown associée au bouton
        const toggle = bootstrap.Dropdown.getOrCreateInstance(dropdown.querySelector('.dropdown-toggle'));
        toggle.show(); // Ouvre le menu
    });
    // Masque le menu quand on quitte le hover
    dropdown.addEventListener('mouseleave', () => {
        const toggle = bootstrap.Dropdown.getOrCreateInstance(dropdown.querySelector('.dropdown-toggle'));
        toggle.hide(); // Ferme le menu
    });
</script>

</body>

</html>

gama/templates/gama/error.html
{% extends "gama/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<div class="container-fluid">
  <div class="inner-content">
      <div class="alert alert-danger" role="alert">
          <h4 class="alert-heading">{%trans "Error!" %}</h4>
              <p>{{ message }}</p>
      </div>
      <a href="{% url 'gama:index' %}" class="btn btn-beige mt-3">{%trans "Back" %}</a>
  </div>
</div>

{% endblock %}